# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: Docker-CI
trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

variables:
  ImageName: 'k123gavali/microservicedemo:$(Build.BuildId)'

stages:
  - stage: Build
    displayName: Build image
    jobs:
      - job: DockerImage
        displayName: Build and push Docker image
        steps:
          - task: Docker@1
            displayName: 'Build the Docker image'
            inputs:
              containerregistrytype: Container Registry
              dockerRegistryEndpoint: 'Docker Hub'
              command: 'Build an image'
              dockerFile: '**/Dockerfile'
              imageName: '$(ImageName)'
              includeLatestTag: true
              useDefaultContext: false
              buildContext: '.'